#!/usr/bin/env node
const http = require('http');
const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');

const AGENT_DIR = process.env.PI_CODING_AGENT_DIR || path.join(os.homedir(), '.pi', 'agent');
const YITEC_DIR = path.join(AGENT_DIR, 'yitec');
const TIERS_PATH = process.env.YITEC_TIERS_PATH || path.join(YITEC_DIR, 'model-tiers.json');
const MODELS_PATH = process.env.YITEC_MODELS_PATH || path.join(AGENT_DIR, 'models.json');
const PORT = Number(process.env.PORT || process.env.YITEC_VAULT_PORT || 7979);
const HOST = process.env.YITEC_VAULT_HOST || '127.0.0.1';
const TOKEN = process.env.YITEC_VAULT_TOKEN || crypto.randomBytes(18).toString('base64url');
const PASSWORD = process.env.YITEC_VAULT_PASSWORD || '';

const defaultTiers = {
  roles: {
    default: { tier: 'high', thinking: 'medium' }, planner: { tier: 'high', thinking: 'high' }, executor: { tier: 'low', thinking: 'low' },
    subagent: { tier: 'low', thinking: 'low' }, reviewer: { tier: 'high', thinking: 'high' }, vision: { tier: 'high', thinking: 'off' },
    commit: { tier: 'low', thinking: 'low' }, tiny: { tier: 'low', thinking: 'off' }
  },
  planner: { tier: 'high', thinking: 'high' }, executor: { tier: 'low', thinking: 'low' }, vision: { models: [] },
  tiers: { high: [], low: [], uncapable: [] },
  retry: { enabled: true, maxPerUserPrompt: 2, cooldownMs: 300000, fallbackChains: {}, errorPatterns: ['rate limit', '429', 'quota', 'weekly limit', 'session limit', 'credits', 'overloaded'] },
  magicKeywords: { enabled: true, ultrathink: true, orchestrate: true, cheap: true },
  advisor: { enabled: false, modelRole: 'reviewer', autoReview: false, tools: ['read', 'grep'] },
  memory: { enabled: true, injectionCharLimit: 5000 }
};

function ensureDir(p) { fs.mkdirSync(path.dirname(p), { recursive: true }); }
function readJson(p, fallback) { try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return fallback; } }
function writeJson(p, value) { ensureDir(p); fs.writeFileSync(p, JSON.stringify(value, null, 2) + '\n'); }
function body(req) { return new Promise((resolve, reject) => { let data=''; req.on('data', c => { data += c; if (data.length > 2_000_000) reject(new Error('body too large')); }); req.on('end', () => { try { resolve(data ? JSON.parse(data) : {}); } catch(e) { reject(e); } }); }); }
function send(res, status, data, type='application/json', headers={}) { res.writeHead(status, { 'content-type': type, 'cache-control': 'no-store', ...headers }); res.end(type === 'application/json' ? JSON.stringify(data) : data); }
function sessionValue() { return crypto.createHmac('sha256', TOKEN).update('yitec-vault-session').digest('base64url'); }
function cookie(req, name) { return Object.fromEntries((req.headers.cookie || '').split(';').map(v => v.trim()).filter(Boolean).map(v => { const i = v.indexOf('='); return [v.slice(0, i), decodeURIComponent(v.slice(i + 1))]; }))[name]; }
function authed(req) { const u = new URL(req.url, `http://${req.headers.host}`); return u.searchParams.get('token') === TOKEN || req.headers.authorization === `Bearer ${TOKEN}` || cookie(req, 'yitec_vault_session') === sessionValue(); }
function mergeCfg(v) { return { ...defaultTiers, ...(v || {}), roles: { ...defaultTiers.roles, ...((v && v.roles) || {}) }, retry: { ...defaultTiers.retry, ...((v && v.retry) || {}) }, tiers: { ...defaultTiers.tiers, ...((v && v.tiers) || {}) } }; }
function estimateCost(cfg) { const rows = []; for (const [tier, arr] of Object.entries(cfg.tiers || {})) for (const e of arr || []) { const p = typeof e === 'string' ? { model: e } : e; const input = Number(p.rate && p.rate.input || 0); const output = Number(p.rate && p.rate.output || 0); rows.push({ tier, model: p.model, sampleCost: Number(((input * 0.2) + (output * 0.05)).toFixed(4)) }); } return rows.sort((a,b)=>a.sampleCost-b.sampleCost); }
function doctor(cfg) { const problems = []; const roles = cfg.roles || {}; for (const name of ['planner','executor','subagent','reviewer','vision','commit','tiny']) if (!roles[name]) problems.push(`missing role ${name}`); for (const [tier, arr] of Object.entries(cfg.tiers || {})) for (const e of arr || []) { const m = typeof e === 'string' ? e : e.model; if (!m || !m.includes('/')) problems.push(`${tier}: ${m || '(blank)'} missing provider/model`); } return { ok: problems.length === 0, problems, paths: { tiers: TIERS_PATH, models: MODELS_PATH } }; }

const loginHtml = String.raw`<!doctype html><html><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>Login · Yitec Vault</title><style>${css()}</style></head><body><main class="login glass"><div class="kicker">Private vault</div><h1>Unlock<br/>Vault</h1><p>Enter your personal vault password.</p><input id="password" type="password" autofocus placeholder="Password"/><button class="primary" onclick="login()">Enter vault</button><p id="err" class="err"></p></main><script>async function login(){const r=await fetch('/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:password.value})});if(r.ok) location.href='/'; else err.textContent='Wrong password';}</script></body></html>`;
function css(){return `:root{--a:88 166 255;--b:161 103 255;--c:29 242 183;--ink:#ecf6ff;--muted:#a9b9ca;--line:rgba(255,255,255,.20);--danger:#ff6b8a}*{box-sizing:border-box}body{margin:0;min-height:100vh;font-family:Inter,ui-sans-serif,system-ui;background:radial-gradient(circle at 15% 5%,rgb(var(--a)/.34),transparent 30%),radial-gradient(circle at 80% 10%,rgb(var(--b)/.28),transparent 32%),radial-gradient(circle at 70% 85%,rgb(var(--c)/.22),transparent 36%),linear-gradient(135deg,#050611,#111827 60%,#07131a);color:var(--ink)}main{width:min(1240px,94vw);margin:0 auto;padding:36px 0 70px}.glass{border:1px solid var(--line);background:linear-gradient(135deg,rgba(255,255,255,.16),rgba(255,255,255,.055));box-shadow:0 24px 80px rgba(0,0,0,.35),inset 0 1px 0 rgba(255,255,255,.25);backdrop-filter:blur(24px) saturate(150%);border-radius:32px}.panel{padding:22px}.hero{display:grid;grid-template-columns:1.1fr .9fr;gap:16px}.split{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:16px}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:12px;margin-top:16px}.card{grid-column:span 4}.card.high{grid-column:span 6}.card.low{grid-column:span 4}.card.uncapable{grid-column:span 3}h1{font-size:clamp(46px,8vw,96px);line-height:.88;margin:0;letter-spacing:-.07em}.kicker{font:800 12px/1 ui-monospace,monospace;letter-spacing:.22em;text-transform:uppercase;color:rgb(var(--c));margin-bottom:14px}.lead,p{color:var(--muted)}button,select,input,textarea{border:1px solid var(--line);background:rgba(255,255,255,.10);color:var(--ink);border-radius:14px;padding:10px 12px;outline:none}textarea{width:100%;min-height:150px;font-family:ui-monospace,monospace}input,select{width:100%;margin-bottom:8px}option{color:#111}button{cursor:pointer;font-weight:800;border-radius:999px}button.primary{background:linear-gradient(135deg,rgb(var(--a)/.78),rgb(var(--b)/.72))}button.danger{background:rgb(255 70 105/.18);color:#ffd6df}.toolbar{display:flex;gap:9px;flex-wrap:wrap;margin-top:16px}.row{display:grid;grid-template-columns:1fr 105px 95px;gap:8px}.pill{display:inline-flex;margin:3px;padding:7px 10px;border:1px solid var(--line);border-radius:999px;color:var(--muted);background:rgba(255,255,255,.08);font-size:12px}.notice{border-left:3px solid rgb(var(--c));padding:12px;color:var(--muted)}label{font-size:12px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);font-weight:800}.check{display:flex;gap:7px;align-items:center;text-transform:none;letter-spacing:0}.check input{width:auto;margin:0}.login{width:min(460px,92vw);padding:30px;position:absolute;left:50%;top:50%;transform:translate(-50%,-50%)}.err{color:#ffb1c1}@media(max-width:850px){.hero,.split{grid-template-columns:1fr}.card,.card.high,.card.low,.card.uncapable{grid-column:span 12}}`;}

const html = String.raw`<!doctype html><html><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>Yitec Model Vault</title><style>${css()}</style></head><body><main><section class="hero"><div class="glass panel"><div class="kicker">Yitec Pi Harness</div><h1>Model<br/>Vault</h1><p class="lead">Roles, tiers, fallback chains, magic keywords, advisor-lite, memory, rates, vision, and local provider credentials.</p><div class="toolbar"><button class="primary" onclick="save()">Save vault</button><button onclick="addProfile()">Add model</button><button onclick="load()">Reload</button><button onclick="runDoctor()">Doctor</button><button onclick="exportCfg()">Export</button></div></div><div class="glass panel"><div class="kicker">Credentials</div><p class="notice">Keep bound to 127.0.0.1. Do not commit models.json. OAuth still belongs in Pi's native /login.</p><label>OpenAI API key or env reference<input id="openaiEnv" type="password" value="$OPENAI_API_KEY"/></label><label class="check"><input id="revealKey" type="checkbox" onchange="openaiEnv.type=this.checked?'text':'password'"/> reveal key</label><button onclick="saveOpenAIProvider()">Save OpenAI credential</button><div id="paths"></div></div></section><section class="split"><div class="glass panel"><div class="kicker">Roles</div><textarea id="rolesText"></textarea></div><div class="glass panel"><div class="kicker">Fallback chains + features</div><label>Fallback chains JSON</label><textarea id="fallbackText"></textarea><div class="row"><label class="check"><input id="magicEnabled" type="checkbox"/> magic keywords</label><label class="check"><input id="memoryEnabled" type="checkbox"/> memory</label><label class="check"><input id="advisorEnabled" type="checkbox"/> advisor</label></div></div></section><section class="split"><div class="glass panel"><div class="kicker">Doctor</div><pre id="doctorOut" class="notice"></pre></div><div class="glass panel"><div class="kicker">Cost sample</div><p class="notice">Estimated for 200k input + 50k output tokens, using each model's $/M profile.</p><div id="costs"></div></div></section><section class="grid" id="cards"></section></main><script>
const token = new URLSearchParams(location.search).get('token') || ''; let cfg;
async function api(path, opts={}){ const r=await fetch(path+'?token='+encodeURIComponent(token),{...opts,headers:{'content-type':'application/json',...(opts.headers||{})}}); if(!r.ok) throw new Error(await r.text()); return r.json(); }
function norm(e,tier){ return typeof e==='string'?{model:e,tier,vision:false,thinking:'',rate:{}}:{tier,...e,rate:e.rate||{}} }
async function load(){ cfg=await api('/api/config'); paths.innerHTML='<span class="pill">tiers '+esc(cfg.paths.tiers)+'</span><span class="pill">models '+esc(cfg.paths.models)+'</span>'; rolesText.value=JSON.stringify(cfg.tiers.roles||{},null,2); fallbackText.value=JSON.stringify((cfg.tiers.retry&&cfg.tiers.retry.fallbackChains)||{},null,2); magicEnabled.checked=cfg.tiers.magicKeywords?.enabled!==false; memoryEnabled.checked=cfg.tiers.memory?.enabled!==false; advisorEnabled.checked=!!cfg.tiers.advisor?.enabled; render(); runDoctor(); }
function all(){ return ['high','low','uncapable'].flatMap(t=>(cfg.tiers.tiers[t]||[]).map(e=>norm(e,t))); }
function render(){ cards.innerHTML=''; all().forEach((p,i)=>{ const el=document.createElement('article'); el.className='glass panel card '+p.tier; el.innerHTML='<label>Model<input data-k="model" value="'+esc(p.model)+'"/></label><div class="row"><label>Tier<select data-k="tier"><option>high</option><option>low</option><option>uncapable</option></select></label><label>Thinking<input data-k="thinking" value="'+esc(p.thinking||'')+'"/></label><label class="check"><input type="checkbox" data-k="vision" '+(p.vision?'checked':'')+'/> vision</label></div><div class="row"><label>$/M input<input data-k="input" value="'+(p.rate.input??'')+'"/></label><label>$/M output<input data-k="output" value="'+(p.rate.output??'')+'"/></label><button class="danger" onclick="removeProfile('+i+')">Remove</button></div>'; cards.appendChild(el); el.querySelector('[data-k=tier]').value=p.tier; }); }
function collect(){ const next={...cfg.tiers, roles:json(rolesText.value,{}), retry:{...(cfg.tiers.retry||{}),fallbackChains:json(fallbackText.value,{})}, magicKeywords:{...(cfg.tiers.magicKeywords||{}),enabled:magicEnabled.checked}, memory:{...(cfg.tiers.memory||{}),enabled:memoryEnabled.checked}, advisor:{...(cfg.tiers.advisor||{}),enabled:advisorEnabled.checked}, tiers:{high:[],low:[],uncapable:[]}, vision:{models:[]}}; document.querySelectorAll('.card').forEach(card=>{ const get=k=>card.querySelector('[data-k='+k+']'); const p={model:get('model').value.trim(), vision:get('vision').checked, thinking:get('thinking').value.trim()||undefined, rate:{input:num(get('input').value), output:num(get('output').value)}}; const tier=get('tier').value; if(!p.model)return; next.tiers[tier].push(p); if(p.vision) next.vision.models.push(p); }); return next; }
function json(s,f){ try{return JSON.parse(s)}catch(e){alert('Bad JSON: '+e.message);throw e} } function num(v){ return v===''?undefined:Number(v) } function esc(s){ return String(s).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m])) }
async function save(){ cfg.tiers=collect(); await api('/api/config',{method:'POST',body:JSON.stringify(cfg.tiers)}); await load(); alert('Saved'); }
function addProfile(){ cfg.tiers.tiers.low.push({model:'provider/model',vision:false,rate:{}}); render(); }
function removeProfile(i){ const arr=all(); arr.splice(i,1); cfg.tiers.tiers={high:[],low:[],uncapable:[]}; arr.forEach(p=>cfg.tiers.tiers[p.tier].push(p)); render(); }
async function saveOpenAIProvider(){ await api('/api/provider/openai',{method:'POST',body:JSON.stringify({apiKey:openaiEnv.value})}); alert('Saved provider reference in models.json'); }
async function runDoctor(){ const d=await api('/api/doctor'); doctorOut.textContent=JSON.stringify(d.doctor,null,2); costs.innerHTML=d.costs.map(c=>'<span class="pill">'+esc(c.tier)+' '+esc(c.model)+' ≈ $'+c.sampleCost+'</span>').join(''); }
function exportCfg(){ const blob=new Blob([JSON.stringify(collect(),null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='model-tiers.json'; a.click(); }
load().catch(e=>document.body.innerHTML='<main><div class="glass panel"><h1>Vault error</h1><p>'+esc(e.message)+'</p></div></main>');
</script></body></html>`;

const server = http.createServer(async (req, res) => {
  try {
    const url = new URL(req.url, `http://${req.headers.host}`);
    if (url.pathname === '/login' && req.method === 'GET') return send(res, 200, loginHtml, 'text/html; charset=utf-8');
    if (url.pathname === '/login' && req.method === 'POST') { const v = await body(req); if (!PASSWORD || v.password !== PASSWORD) return send(res, 401, { error: 'Invalid password' }); return send(res, 200, { ok: true }, 'application/json', { 'set-cookie': `yitec_vault_session=${encodeURIComponent(sessionValue())}; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000` }); }
    if (url.pathname === '/logout') return send(res, 302, '', 'text/plain', { location: '/login', 'set-cookie': 'yitec_vault_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0' });
    if (url.pathname === '/') return authed(req) ? send(res, 200, html, 'text/html; charset=utf-8') : send(res, 302, '', 'text/plain', { location: '/login' });
    if (!authed(req)) return send(res, 401, { error: 'Unauthorized. Login at /login or use token auth.' });
    if (url.pathname === '/api/config' && req.method === 'GET') { const tiers = mergeCfg(readJson(TIERS_PATH, defaultTiers)); return send(res, 200, { tiers, models: readJson(MODELS_PATH, { providers: {} }), paths: { tiers: TIERS_PATH, models: MODELS_PATH } }); }
    if (url.pathname === '/api/config' && req.method === 'POST') { const v = await body(req); writeJson(TIERS_PATH, mergeCfg(v)); return send(res, 200, { ok: true }); }
    if (url.pathname === '/api/doctor') { const cfg = mergeCfg(readJson(TIERS_PATH, defaultTiers)); return send(res, 200, { doctor: doctor(cfg), costs: estimateCost(cfg) }); }
    if (url.pathname === '/api/provider/openai' && req.method === 'POST') { const v = await body(req); const m = readJson(MODELS_PATH, { providers: {} }); m.providers ||= {}; m.providers.openai = { ...(m.providers.openai || {}), apiKey: v.apiKey || '$OPENAI_API_KEY' }; writeJson(MODELS_PATH, m); return send(res, 200, { ok: true }); }
    send(res, 404, { error: 'not found' });
  } catch (e) { send(res, 500, { error: e && e.message || String(e) }); }
});
server.listen(PORT, HOST, () => { const displayHost = HOST === '0.0.0.0' ? '127.0.0.1' : HOST; console.log(`Yitec Model Vault: http://${displayHost}:${PORT}/?token=${TOKEN}`); console.log(`Tiers: ${TIERS_PATH}`); console.log(`Models: ${MODELS_PATH}`); });
